# Generated by Django 4.1.4 on 2023-01-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleoptechapp', '0004_remove_comment_user_id_comment_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_user',
            field=models.CharField(max_length=500),
        ),
    ]
