# Generated by Django 4.1.4 on 2023-01-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleoptechapp', '0005_alter_comment_body_alter_comment_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cleoptechapp.product'),
        ),
    ]
