# Generated by Django 4.1.4 on 2023-01-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleoptechapp', '0008_remove_comment_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.IntegerField(default=1),
        ),
    ]
