# Generated by Django 4.1.4 on 2023-01-06 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cleoptechapp', '0011_rename_product_comment_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product_id',
            new_name='productid',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='userid',
        ),
    ]
