# Generated by Django 4.1.4 on 2023-01-06 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cleoptechapp', '0014_rename_productid_comment_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cleoptechapp.product'),
        ),
    ]
